
package ec.edu.ups.clienteSOAP;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:42:12.887-05:00
 * Generated source version: 3.5.0
 *
 */
public final class VehiculoSoap_VehiculoSoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.Prueba2Soap.ups.edu.ec/", "VehiculoSoapService");

    private VehiculoSoap_VehiculoSoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VehiculoSoapService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VehiculoSoapService ss = new VehiculoSoapService(wsdlURL, SERVICE_NAME);
        VehiculoSoap port = ss.getVehiculoSoapPort();

        {
        System.out.println("Invoking listarVehiculos...");
        java.util.List<ec.edu.ups.clienteSOAP.Vehiculo> listarVehiculo = port.listarVehiculos();
        System.out.println("listarVehiculos.result=" + listarVehiculo);


        }
        {
        System.out.println("Invoking insertarVehiculo...");
        ec.edu.ups.clienteSOAP.Vehiculo insertarVehiculo = null;
        
        
        
        java.lang.String _insertarVehiculo__return = port.insertarVehiculo(insertarVehiculo);
        System.out.println("insertarVehiculo.result=" + _insertarVehiculo__return);


        }

        System.exit(0);
    }

}
