package ec.edu.ups.clienteSOAP;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-01T11:42:12.952-05:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "VehiculoSoapService",
                  wsdlLocation = "http://localhost:8080/Prueba2Soap/VehiculoSoap?wsdl",
                  targetNamespace = "http://soap.Prueba2Soap.ups.edu.ec/")
public class VehiculoSoapService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.Prueba2Soap.ups.edu.ec/", "VehiculoSoapService");
    public final static QName VehiculoSoapPort = new QName("http://soap.Prueba2Soap.ups.edu.ec/", "VehiculoSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Prueba2Soap/VehiculoSoap?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VehiculoSoapService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Prueba2Soap/VehiculoSoap?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VehiculoSoapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VehiculoSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehiculoSoapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VehiculoSoapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VehiculoSoapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VehiculoSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VehiculoSoap
     */
    @WebEndpoint(name = "VehiculoSoapPort")
    public VehiculoSoap getVehiculoSoapPort() {
        return super.getPort(VehiculoSoapPort, VehiculoSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehiculoSoap
     */
    @WebEndpoint(name = "VehiculoSoapPort")
    public VehiculoSoap getVehiculoSoapPort(WebServiceFeature... features) {
        return super.getPort(VehiculoSoapPort, VehiculoSoap.class, features);
    }

}
